version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://db:3306/taskmanager
      - DB_USER=taskuser
      - DB_PASSWORD=taskpass
    restart: unless-stopped
    command: ["/usr/local/bin/wait-for-it.sh", "db:3306", "--", "catalina.sh", "run"]

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=taskmanager
      - MYSQL_USER=taskuser
      - MYSQL_PASSWORD=taskpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
