---
# Default variables (can be overridden)
workspace: "/home/vagrant/deploy_app"
IMAGE: "deependrabhatta/java_app:{{ build_number }}"
compose_file: "compose.yaml"
env_file: ".env"
wait: "wait-for-it.sh"
sql: "init.sql"
